os: linux
dist: bionic
language: cpp
env: PARLAY_NUM_THREADS=8

stages:
  - test
  - analysis
  - sanitize
  - report

addons:
  apt:
    update: true
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - g++-7
    - g++-9
    - clang-10
    - libomp-10-dev
    - libtbb-dev
    - libc++1-10
    - libc++abi1-10
    - libc++-10-dev
    - libc++abi-10-dev
  homebrew:
    update: true
    packages:
    - gcc@9


before_script:
  # Install the latest CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget --quiet https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz
      tar -xf cmake-3.18.2-Linux-x86_64.tar.gz
      export PATH=$PWD/cmake-3.18.2-Linux-x86_64/bin/:$PATH
    fi
  
jobs:
  include:
  
    # -------------------------------------------------------------------------
    #                                TEST STAGE
    # -------------------------------------------------------------------------
  
    # Test that the project builds and tests successfully with GCC
    - stage: test
      name: check-gcc
      script:
      - mkdir build
      - cd build
      - CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_TEST_OMP=On -DPARLAY_TEST_TBB=On -DPARLAY_BENCHMARK=On ..
      - make
      - ctest --no-tests=error --output-on-failure
      
    # Test that the project builds and tests successfully with Clang
    - stage: test
      name: check-clang
      script:
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_TEST_OMP=On -DPARLAY_TEST_TBB=On -DPARLAY_BENCHMARK=On ..
      - make
      - ctest --no-tests=error --output-on-failure
      
    # Test that the project builds and tests successfully with Clang using libc++
    - stage: test
      name: check-clang-libcxx
      script:
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DUSE_LIBCXX=On -DPARLAY_TEST_OMP=On -DPARLAY_TEST_TBB=On -DPARLAY_BENCHMARK=On ..
      - make
      - ctest --no-tests=error --output-on-failure
      
    # Test that the project builds and tests successfully with GCC 7 (with Cilk support)
    - stage: test
      name: check-gcc-cilk
      script:
      - mkdir build
      - cd build
      - CC=gcc-7 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_TEST_CILK=On ..
      - make
      - ctest --no-tests=error --output-on-failure
      
    # Test that the project builds and tests successfully on OSX with GCC
    - stage: test
      name: check-apple-gcc
      os: osx
      osx_image: xcode12u
      script:
      - mkdir build
      - cd build
      - CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On ..
      - make
      - ctest --no-tests=error --output-on-failure
      
    # Test that the project builds and tests successfully on OSX with Apple Clang
    - stage: test
      name: check-apple-clang
      os: osx
      osx_image: xcode12u
      script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On ..
      - make
      - ctest --no-tests=error --output-on-failure

    # Test that the project builds and tests successfully with Clang in Release mode (optimized)
    - stage: test
      name: check-release
      script:
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Release -DPARLAY_TEST=On -DPARLAY_TEST_OMP=On -DPARLAY_TEST_TBB=On -DPARLAY_BENCHMARK=On ..
      - make
      - ctest --no-tests=error --output-on-failure

    # -------------------------------------------------------------------------
    #                            ANALYSIS STAGE
    # -------------------------------------------------------------------------
    
    # Run CppCheck on the codebase
    - stage: analysis
      name: cppcheck
      script:
      # Download, build, and install cppcheck
      - wget --quiet https://github.com/danmar/cppcheck/archive/2.1.tar.gz
      - tar -xf 2.1.tar.gz
      - mkdir cppcheck-2.1/build && pushd cppcheck-2.1/build
      - CC=clang-10 CXX=clang++-10 cmake .. -DCMAKE_BUILD_TYPE=Release
      - make && sudo make install
      - popd

      # Run the analysis
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DENABLE_CPPCHECK=On ..
      - make cppcheck-all
      
    # Run clang-tidy on the codebase
    - stage: analysis
      name: clang-tidy
      script:
      # Install clang-tidy
      - sudo apt-get -qq install clang-tidy-10
      - sudo ln -s /usr/bin/clang-tidy-10 /usr/bin/clang-tidy

      # Run the analysis
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DENABLE_CLANG_TIDY=On -DCLANG_TIDY_EXE=/usr/bin/clang-tidy ..
      - make clang-tidy-all

    # Run include-what-you-use on the codebase
    - stage: analysis
      name: include-what-you-use
      script:
      # Install clang and llvm development files
      - sudo apt-get -qq install clang-10 libc++1-10 libc++-10-dev libc++abi1-10 libc++abi-10-dev llvm-10-dev libclang-10-dev

      # Download, build, and install IWYU
      - git clone https://github.com/include-what-you-use/include-what-you-use.git
      - mkdir include-what-you-use/build && pushd include-what-you-use/build
      - git checkout clang_10
      - cmake -DCMAKE_PREFIX_PATH=/usr/lib/llvm-10 ..
      - make && sudo make install
      - popd

      # Run the analysis
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DENABLE_IWYU=On ..
      - make iwyu-all

    # -------------------------------------------------------------------------
    #                              SANITIZE STAGE
    # -------------------------------------------------------------------------

    # Run the tests with AddressSanitizer instrumentation
    - stage: sanitize
      name: check-asan
      script:
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DBUILD_ASAN_TESTS=On -DUSE_LIBCXX=On ..
      - make
      - ctest --no-tests=error --output-on-failure -R -asan 
      
    # Run the tests with UndefinedBehaviorSanitizer instrumentation  
    - stage: sanitize
      name: check-ubsan
      script:
      - mkdir build
      - cd build
      - CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DBUILD_UBSAN_TESTS=On -DUSE_LIBCXX=On ..
      - make
      - ctest --no-tests=error --output-on-failure -R -ubsan


    # -------------------------------------------------------------------------
    #                              REPORT STAGE
    # -------------------------------------------------------------------------

    # Report code coverage results to codecov.io
    - stage: report
      name: code-coverage
      script:
      - sudo apt install lcov
      - mkdir build
      - cd build
      - CC=gcc CXX=g++ cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=" --coverage " -DPARLAY_TEST=On ..
      - make
      - make check
      - lcov --directory . --capture --output-file coverage.info
      - lcov --remove coverage.info '/usr/*' '*/googletest/*' '*/test/*' --output-file coverage.info
      - lcov --list coverage.info
      - bash <(curl -s https://codecov.io/bash) -f coverage.info
